name: 'run BiliExp'

on:
  schedule:
    - cron: '0 1 * * *' #上午9:00执行，修改时注意时区
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 执行BiliExp
      run: bash ./run_in_Actions/run_BiliExp.sh
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}